# Generated by Django 3.0.7 on 2020-06-22 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_spoken_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cs_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
